version: '2'

services:
   adminer:
    image: adminer
    env_file: ./.env
    container_name: adminer
    restart: always
    ports:
       - "${ADMINER_PORT}:8080"
    networks:
       - devbox_network

networks:
   devbox_network:
     external: true
